import BuildingBlocks.ActualEq22PairDilation
import BuildingBlocks.ActualEq22ForwardMellin
import BuildingBlocks.ActualEq22ArithmeticIdentity
import BuildingBlocks.ActualEq22MellinInversion
import BuildingBlocks.ActualEq22OriginalMellin

/-! Audit every public theorem in the native original Eq22 a = 0 bundle.
Initial-line identification/inversion only. The existing analytic upper remains
written and unformalized; stronger estimates, the eventual sign and RH remain open. -/

#print axioms BuildingBlocks.ActualEq22PairDilation.weightedLambda_mul
#print axioms BuildingBlocks.ActualEq22PairDilation.weightedLambda_zeta
#print axioms BuildingBlocks.ActualEq22PairDilation.pair_divisor_assoc
#print axioms BuildingBlocks.ActualEq22PairDilation.scoreMass_stable
#print axioms BuildingBlocks.ActualEq22PairDilation.cutoff_score_dilation
#print axioms BuildingBlocks.ActualEq22PairDilation.divisor_sum_eq_cutoff
#print axioms BuildingBlocks.ActualEq22PairDilation.score_dilation_eq_full_pair
#print axioms BuildingBlocks.ActualEq22PairDilation.TnumOn_eq_DnumOn_sub_full_pair
#print axioms BuildingBlocks.ActualEq22PairDilation.Tnum_eq_Dnum_sub_full_pair
#print axioms BuildingBlocks.ActualEq22ForwardMellin.countBaseline_eq_step
#print axioms BuildingBlocks.ActualEq22ForwardMellin.countBaseline_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.countBaseline_eq
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Acore_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Zcore_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_countBaseline
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_Acore
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_Zcore
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_criticalCutoff
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_A
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_Z
#print axioms BuildingBlocks.ActualEq22ForwardMellin.continuous_C
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_countBaseline
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_Acore
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_A
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_Zcore
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_Z
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_C
#print axioms BuildingBlocks.ActualEq22ForwardMellin.centered_add_one_eq
#print axioms BuildingBlocks.ActualEq22ForwardMellin.hasMellin_C_a0
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Acore_eq_Jfinite
#print axioms BuildingBlocks.ActualEq22ForwardMellin.criticalCutoff_eq_Icc
#print axioms BuildingBlocks.ActualEq22ForwardMellin.A_eq_actual_Aold
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Z_eq_actual_Z
#print axioms BuildingBlocks.ActualEq22ForwardMellin.C_eq_corrected_actual_row
#print axioms BuildingBlocks.ActualEq22ForwardMellin.criticalCutoff_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.A_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Z_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.C_zero
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Acore_real
#print axioms BuildingBlocks.ActualEq22ForwardMellin.A_real
#print axioms BuildingBlocks.ActualEq22ForwardMellin.Z_real
#print axioms BuildingBlocks.ActualEq22ForwardMellin.C_real
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.cofactor_row
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.baseline_scalar
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.fullNumerator_eq_sample
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.Aold_eq_score_sub_mass
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.fullNumerator_eq_six_rows
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.literal_identity_of_native_pair_row
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.literal_identity_with_pair_defect
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.literal_identity
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.literal_normalized_identity
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.complex_literal_identity
#print axioms BuildingBlocks.ActualEq22ArithmeticIdentity.literal_eq_forwardC
#print axioms BuildingBlocks.ActualEq22MellinInversion.norm_centered_add_one_le
#print axioms BuildingBlocks.ActualEq22MellinInversion.norm_fullFactor0_le
#print axioms BuildingBlocks.ActualEq22MellinInversion.analyticAt_fullFactor0
#print axioms BuildingBlocks.ActualEq22MellinInversion.continuous_fullFactor0_vertical
#print axioms BuildingBlocks.ActualEq22MellinInversion.integrable_fullFactor0_vertical
#print axioms BuildingBlocks.ActualEq22MellinInversion.mellin_C_vertical_eq
#print axioms BuildingBlocks.ActualEq22MellinInversion.verticalIntegrable_C
#print axioms BuildingBlocks.ActualEq22MellinInversion.C_mellin_convergent
#print axioms BuildingBlocks.ActualEq22MellinInversion.mellinInv_C
#print axioms BuildingBlocks.ActualEq22MellinInversion.norm_perronKernel0_le
#print axioms BuildingBlocks.ActualEq22MellinInversion.integrable_perronKernel0
#print axioms BuildingBlocks.ActualEq22MellinInversion.mellinInv_kernel_eq_perron0_neg
#print axioms BuildingBlocks.ActualEq22MellinInversion.integrable_mellinInv_C_kernel
#print axioms BuildingBlocks.ActualEq22MellinInversion.C_eq_perron
#print axioms BuildingBlocks.ActualEq22MellinInversion.perronFactor0_eq_fullFactor0
#print axioms BuildingBlocks.ActualEq22MellinInversion.perronKernel0_eq_closed_form
#print axioms BuildingBlocks.ActualEq22MellinInversion.C_eq_closed_perron
#print axioms BuildingBlocks.ActualEq22MellinInversion.integrable_closed_perron0
#print axioms BuildingBlocks.ActualEq22OriginalMellin.original_eq_forward
#print axioms BuildingBlocks.ActualEq22OriginalMellin.continuous_original
#print axioms BuildingBlocks.ActualEq22OriginalMellin.hasMellin_original
#print axioms BuildingBlocks.ActualEq22OriginalMellin.verticalIntegrable_original
#print axioms BuildingBlocks.ActualEq22OriginalMellin.mellinInv_original
#print axioms BuildingBlocks.ActualEq22OriginalMellin.original_eq_closed_perron
#print axioms BuildingBlocks.ActualEq22OriginalMellin.original_closed_perron_integrable
#print axioms BuildingBlocks.ActualEq22OriginalMellin.original_normalized_eq_closed_perron

#check BuildingBlocks.ActualEq22PairDilation.Tnum_eq_Dnum_sub_full_pair
#check BuildingBlocks.ActualEq22ArithmeticIdentity.literal_identity_of_native_pair_row
#check BuildingBlocks.ActualEq22ArithmeticIdentity.literal_identity
#check BuildingBlocks.ActualEq22ArithmeticIdentity.literal_normalized_identity
#check BuildingBlocks.ActualEq22ArithmeticIdentity.literal_eq_forwardC
#check BuildingBlocks.ActualEq22OriginalMellin.original
#check BuildingBlocks.ActualEq22OriginalMellin.original_eq_forward
#check BuildingBlocks.ActualEq22OriginalMellin.continuous_original
#check BuildingBlocks.ActualEq22OriginalMellin.hasMellin_original
#check BuildingBlocks.ActualEq22OriginalMellin.verticalIntegrable_original
#check BuildingBlocks.ActualEq22OriginalMellin.mellinInv_original
#check BuildingBlocks.ActualEq22OriginalMellin.original_eq_closed_perron
#check BuildingBlocks.ActualEq22OriginalMellin.original_closed_perron_integrable
#check BuildingBlocks.ActualEq22OriginalMellin.original_normalized_eq_closed_perron
