import BuildingBlocks.ActualPrimePowerWindowGeometry

#check BuildingBlocks.ActualPrimePowerWindowGeometry.prime_power_window_subset_cutoff
#check BuildingBlocks.ActualPrimePowerWindowGeometry.distinct_windows_disjoint_interiors
#check BuildingBlocks.ActualPrimePowerWindowGeometry.actual_proper_prime_power_unique_row
#check BuildingBlocks.ActualPrimePowerWindowGeometry.no_actual_proper_prime_power_before_four
#check BuildingBlocks.ActualPrimePowerWindowGeometry.prime_closed_windows_disjoint
#check BuildingBlocks.ActualPrimePowerWindowGeometry.actual_different_exponents_overlap

#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.four_le_pow
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.four_le_prime_pow
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.one_le_window_left
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.leftWindow_subset_one_to_n
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.leftWindow_subset_real_cutoff
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.pow_eq_mul_pred_pow
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.pow_add_pred_pow_le_pow
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.pow_add_pred_pow_lt_pow
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.sqrt_pow_le_pred_pow
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.earlier_pow_le_later_window_left
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.earlier_pow_lt_later_window_left
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.ordered_closed_windows_disjoint
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.prime_closed_windows_disjoint
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.ordered_windows_disjoint_interiors
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.distinct_windows_disjoint_interiors
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.prime_power_window_subset_cutoff
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.prime_power_representation_unique
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.actual_proper_prime_power_unique_row
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.actual_proper_prime_power_four_le
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.no_actual_proper_prime_power_before_four
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.window_four
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.seven_mem_window_eight
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.seven_mem_window_nine
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.actual_different_exponents_overlap
#print axioms BuildingBlocks.ActualPrimePowerWindowGeometry.different_exponents_not_disjoint
