import BuildingBlocks.ActualMobiusLargePrimeSector

#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.quotient_lt_of_large_prime
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.quotient_pos_of_prime_dvd
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.large_prime_coprime_quotient
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.large_prime_coefficient
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.prime_divisor_le_large_prime
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.large_prime_unique
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.pairProduct_mem_largeSector
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.pairProduct_injective
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.pairProduct_surjective
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.pair_coefficient
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.weighted_large_sector_reindex
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.weighted_complete_partition
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.unit_not_largeSector
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.unit_mem_smallSector
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.sectors_zero
#print axioms BuildingBlocks.ActualMobiusLargePrimeSector.sectors_one
