import BuildingBlocks.ActualOmegaInverse

#print axioms BuildingBlocks.ActualOmegaInverse.primeIndicator_apply
#print axioms BuildingBlocks.ActualOmegaInverse.primeIndicator_one
#print axioms BuildingBlocks.ActualOmegaInverse.primeIndicator_apply_prime
#print axioms BuildingBlocks.ActualOmegaInverse.omegaPlusOne_one
#print axioms BuildingBlocks.ActualOmegaInverse.omegaPlusOne_apply_prime
#print axioms BuildingBlocks.ActualOmegaInverse.omegaPlusOne_apply_prime_pow
#print axioms BuildingBlocks.ActualOmegaInverse.inverseValue_eq
#print axioms BuildingBlocks.ActualOmegaInverse.inverseValue_zero
#print axioms BuildingBlocks.ActualOmegaInverse.inverseValue_one
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_apply
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_one
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_recurrence
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_mul_omegaPlusOne
#print axioms BuildingBlocks.ActualOmegaInverse.omegaPlusOne_mul_actualInverse
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_unique
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_apply_prime
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_apply_prime_sq
#print axioms BuildingBlocks.ActualOmegaInverse.omega_eq_zeta_mul_primeIndicator
#print axioms BuildingBlocks.ActualOmegaInverse.omegaPlusOne_eq_zeta_mul_unit_add_primeIndicator
#print axioms BuildingBlocks.ActualOmegaInverse.actualInverse_mul_unit_add_primeIndicator
#print axioms BuildingBlocks.ActualOmegaInverse.inverseSummatory_zero
#print axioms BuildingBlocks.ActualOmegaInverse.inverseSummatory_one
#print axioms BuildingBlocks.ActualOmegaInverse.mertens_zero
#print axioms BuildingBlocks.ActualOmegaInverse.mertens_eq_inverseSummatory_add_primeCofactors
#print axioms BuildingBlocks.ActualOmegaInverse.G_div_natCast
#print axioms BuildingBlocks.ActualOmegaInverse.M_eq_G_add_primeCofactors
#print axioms BuildingBlocks.ActualOmegaInverse.G_eq_zero_of_lt_one
#print axioms BuildingBlocks.ActualOmegaInverse.M_eq_zero_of_lt_one

#check BuildingBlocks.ActualOmegaInverse.actualInverse_mul_omegaPlusOne
#check BuildingBlocks.ActualOmegaInverse.actualInverse_one
#check BuildingBlocks.ActualOmegaInverse.actualInverse_apply_prime
#check BuildingBlocks.ActualOmegaInverse.actualInverse_apply_prime_sq
#check BuildingBlocks.ActualOmegaInverse.actualInverse_mul_unit_add_primeIndicator
#check BuildingBlocks.ActualOmegaInverse.mertens_eq_inverseSummatory_add_primeCofactors
#check BuildingBlocks.ActualOmegaInverse.M_eq_G_add_primeCofactors
#check BuildingBlocks.ActualOmegaInverse.G_eq_zero_of_lt_one
#check BuildingBlocks.ActualOmegaInverse.M_eq_zero_of_lt_one
