import BuildingBlocks.ActualProperPrimePowerForcing

#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.mem_primeBases
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.base_le_power
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.exponent_le_power
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.mem_primeBases_iff_real_cutoff
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_exponent_le_cutoff
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_row_vonMangoldt
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.primeBases_subset_square
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.primeBases_eq_empty_of_lt_four
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.primeBases_eq_empty_of_exponent_gt
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_full_enumeration_iff
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.centeredError_abs_le_full
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.centeredError_sq_full_intervalIntegrable
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.energyDensity_full_intervalIntegrable
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.energyDensity_nonneg
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.fullEnergy_nonneg
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.rowInterval_subset_full
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.rowIntervals_pairwise_disjoint
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.windowEnergy_eq_rowIntegral
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_grade_energy_allocation
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.trace_coefficient_sq
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_grade_trace_cauchy
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_grade_absolute_force_le
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.primeHarmonicSecondMass_nonneg
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.gradeCoefficient_nonneg
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_row_coefficient_decay
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_grade_coefficient_decay
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.primeHarmonicSecondMass_le_native
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.primeHarmonicSecondMass_le_nine_log_sq
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.sqrt_primeHarmonicSecondMass_le_three_log
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.gradeGeometricRatio_nonneg
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.gradeGeometricRatio_fourth
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.gradeGeometricRatio_le_seven_eighths
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.finite_geometric_grade_identity
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.finite_geometric_grade_le_eight
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.sqrt_geometricDecay_eq
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_all_grade_coefficients_le_twenty_four_log
#print axioms BuildingBlocks.ActualProperPowerEnergyAllocation.actual_full_absolute_force_le_with_remainder
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.log_comparison
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.weight_le_envelope
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.envelope_intervalIntegrable
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.rpow_half_div
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.potentialOne_hasDerivAt
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.potentialTwo_hasDerivAt
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.envelopeOne_integral
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.envelopeTwo_integral
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.weight_le_intervalIntegral
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_telescoping_bound
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.potentialOne_nonpos
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.potentialTwo_nonpos
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_log_tail_le_six
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_log_sq_tail_le_twenty_six
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_geometric_tail_remainder
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_weighted_geometric_tail_remainder
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_geometric_tail_le_four
#print axioms BuildingBlocks.ActualLogarithmicTailBounds.finite_weighted_geometric_tail_le_twenty_four
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.rawRemainderRow_nonneg
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.gradeRemainder_nonneg
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.power_rpow_half
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_remainder_row_le
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_grade_remainder_le_integer_sum
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.primeBaseRatio_nonneg
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.primeBaseRatio_sq
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.primeBaseRatio_le_three_quarters
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.primeBaseRatio_pow
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.primeBaseRatio_cube
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.harmonicBaseMass_le_native
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.native_harmonicMass_le_seventeen_log_sq
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.rawRemainderRow_two
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_square_grade_remainder_le_masses
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_square_grade_remainder_le_thirty_five_log_sq
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.rawRemainderRow_eq_geometric
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.finite_rawRemainder_high_degrees
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_high_grade_remainder_le_648
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.all_grade_remainders_le_square_add_high
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_all_grade_remainders_le_three_thousand_log_sq
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_full_absolute_force_bound
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.abs_signedProperPowerForce_le_fullAbsoluteForce
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_signed_proper_power_force_bound
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.finite_energy_young
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_full_absolute_force_young
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_signed_proper_power_force_young
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.signedProperPowerForce_eq_actualLambda_sum
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_proper_power_force_bound
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_proper_power_force_young
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.fullAbsoluteForce_eq_actualLambda_abs_sum
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_absolute_rows_bound
#print axioms BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_absolute_rows_young
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_full_absolute_force_bound
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_signed_proper_power_force_bound
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_full_absolute_force_young
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_signed_proper_power_force_young
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_proper_power_force_bound
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_proper_power_force_young
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_absolute_rows_bound
#check BuildingBlocks.ActualProperPrimePowerForcing.actual_lambda_absolute_rows_young
