import BuildingBlocks.ActualFullPerronTruncation

/-! Audit all public theorems of the actual finite-height Perron companion.

Initial-line approximation only. The existing analytic upper remains proved
in written analysis and unformalized; stronger arithmetic estimates, the
eventual signed premise and RH remain open. -/

#print axioms BuildingBlocks.PerronTruncationInterval.integral_sub_setIntegral_eq_compl
#print axioms BuildingBlocks.PerronTruncationInterval.norm_integral_sub_setIntegral_le_compl
#print axioms BuildingBlocks.PerronTruncationInterval.integral_sub_integral_Icc_eq_compl
#print axioms BuildingBlocks.PerronTruncationInterval.norm_integral_sub_integral_Icc_le_compl
#print axioms BuildingBlocks.PerronTruncationInterval.intervalIntegral_eq_integral_Icc
#print axioms BuildingBlocks.PerronTruncationInterval.symmetric_intervalIntegral_eq_integral_Icc
#print axioms BuildingBlocks.PerronTruncationInterval.integral_sub_symmetric_interval_eq_compl
#print axioms BuildingBlocks.PerronTruncationInterval.norm_integral_sub_symmetric_interval_le_compl
#print axioms BuildingBlocks.PerronTruncationInterval.scaled_residual_eq_compl
#print axioms BuildingBlocks.PerronTruncationInterval.norm_scaled_residual_le_compl
#print axioms BuildingBlocks.PerronTruncationInterval.norm_perron_normalized_residual_le_compl
#print axioms BuildingBlocks.PerronTruncationInterval.fullNumerator_truncation_residual_eq_compl
#print axioms BuildingBlocks.PerronTruncationInterval.fullNumerator_truncation_residual_le_compl
#print axioms BuildingBlocks.PerronTruncationTail.weight_nonneg
#print axioms BuildingBlocks.PerronTruncationTail.integrable_weight
#print axioms BuildingBlocks.PerronTruncationTail.positive_tail_le
#print axioms BuildingBlocks.PerronTruncationTail.negative_tail_eq_positive_tail
#print axioms BuildingBlocks.PerronTruncationTail.complement_Icc_eq_tails
#print axioms BuildingBlocks.PerronTruncationTail.integral_complement_Icc_eq_twice_positive_tail
#print axioms BuildingBlocks.PerronTruncationTail.two_tail_le
#print axioms BuildingBlocks.PerronTruncationTail.two_tail_le_of_one_le
#print axioms BuildingBlocks.PerronTruncationTail.two_tail_le_literal
#print axioms BuildingBlocks.ActualFullPerronTruncation.verticalAllowance_nonneg
#print axioms BuildingBlocks.ActualFullPerronTruncation.integral_norm_perron_complement_le
#print axioms BuildingBlocks.ActualFullPerronTruncation.fullNumerator_truncation_error_le_of_pos
#print axioms BuildingBlocks.ActualFullPerronTruncation.fullNumerator_truncation_error_le

#check BuildingBlocks.ActualFullPerronTruncation.fullNumerator_truncation_error_le_of_pos
#check BuildingBlocks.ActualFullPerronTruncation.fullNumerator_truncation_error_le
