import BuildingBlocks.ActualPrimeErrorCausalTrace

#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.psi_increment_le
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.centeredError_intervalIntegrable
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.centeredError_measurable
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.causal_difference_le
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.centeredError_abs_le
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.centeredError_sq_intervalIntegrable
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.energyDensity_eq
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.energyDensity_intervalIntegrable
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.interval_abs_integral_sq_le_integrable
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.windowEnergy_nonneg
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.energyDensity_mul
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.unnormalized_square_integral_le
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.normalization_factor
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.normalized_remainder_factor
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.actual_causal_trace
#print axioms BuildingBlocks.ActualPrimeErrorCausalTrace.actual_causal_trace_literal
#check BuildingBlocks.ActualPrimeErrorCausalTrace.actual_causal_trace
#check BuildingBlocks.ActualPrimeErrorCausalTrace.actual_causal_trace_literal
