import BuildingBlocks.ActualPrimeWorkBalance

#print axioms BuildingBlocks.ActualContinuousWorkBalance.psi_zero
#print axioms BuildingBlocks.ActualContinuousWorkBalance.psi_one
#print axioms BuildingBlocks.ActualContinuousWorkBalance.squareJump_zero
#print axioms BuildingBlocks.ActualContinuousWorkBalance.squareJump_one
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_square_jump
#print axioms BuildingBlocks.ActualContinuousWorkBalance.squareJump_prefix
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_lambda_prefix
#print axioms BuildingBlocks.ActualContinuousWorkBalance.finite_abel_positive
#print axioms BuildingBlocks.ActualContinuousWorkBalance.powerWeight_hasDerivAt
#print axioms BuildingBlocks.ActualContinuousWorkBalance.linearWeight_hasDerivAt
#print axioms BuildingBlocks.ActualContinuousWorkBalance.baselineStorage_hasDerivAt
#print axioms BuildingBlocks.ActualContinuousWorkBalance.powerWeight_continuousOn
#print axioms BuildingBlocks.ActualContinuousWorkBalance.powerWeightDerivative_continuousOn
#print axioms BuildingBlocks.ActualContinuousWorkBalance.linearWeightDerivative_continuousOn
#print axioms BuildingBlocks.ActualContinuousWorkBalance.baselineStorageDerivative_continuousOn
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_square_abel
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_linear_abel
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_baseline_ftc
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_density_work_intervalIntegrable
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_unnormalized_energy_intervalIntegrable
#print axioms BuildingBlocks.ActualContinuousWorkBalance.derivative_combination
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_predictable_work_balance_unrestricted
#print axioms BuildingBlocks.ActualContinuousWorkBalance.actual_predictable_work_balance
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.mem_ordinaryPrimes
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.mem_properIntegers
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.proper_iff_primePow_nonprime
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_lambda_zero_outside_prime_or_proper
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_lambda_prime_proper_split
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_proper_weighted_reindex
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.work_atom_normalization
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_proper_rows_eq_existing_force
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_all_work_rows_eq_prime_plus_proper
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_complete_work_split
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_complete_work_split_literal
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_balance_in_work_notation
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_ordinary_prime_energy_consumer
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_ordinary_prime_energy_consumer_literal
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.ordinaryWork_eq_log_prime_sum
#print axioms BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_ordinary_prime_energy_consumer_log_literal
#check BuildingBlocks.ActualContinuousWorkBalance.actual_predictable_work_balance_unrestricted
#check BuildingBlocks.ActualContinuousWorkBalance.actual_predictable_work_balance
#check BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_complete_work_split
#check BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_complete_work_split_literal
#check BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_ordinary_prime_energy_consumer
#check BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_ordinary_prime_energy_consumer_literal
#check BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.ordinaryWork_eq_log_prime_sum
#check BuildingBlocks.ActualOrdinaryPrimeWorkConsumer.actual_ordinary_prime_energy_consumer_log_literal
