import BuildingBlocks

#check BuildingBlocks.zeta_analytic_off_pole
#print axioms BuildingBlocks.zeta_analytic_off_pole
#check BuildingBlocks.zeta_not_locally_zero
#print axioms BuildingBlocks.zeta_not_locally_zero
#check BuildingBlocks.analytic_logDerivative_principal_part
#print axioms BuildingBlocks.analytic_logDerivative_principal_part
#check BuildingBlocks.zeta_jointMellin_principal_part
#print axioms BuildingBlocks.zeta_jointMellin_principal_part

#check BuildingBlocks.FloorCorrection.logFactorial
#print axioms BuildingBlocks.FloorCorrection.logFactorial
#check BuildingBlocks.FloorCorrection.logFactorial_eq_log
#print axioms BuildingBlocks.FloorCorrection.logFactorial_eq_log
#check BuildingBlocks.FloorCorrection.divisorSum
#print axioms BuildingBlocks.FloorCorrection.divisorSum
#check BuildingBlocks.FloorCorrection.centeredDivisorForcing
#print axioms BuildingBlocks.FloorCorrection.centeredDivisorForcing
#check BuildingBlocks.FloorCorrection.divisorMainTerm
#print axioms BuildingBlocks.FloorCorrection.divisorMainTerm
#check BuildingBlocks.FloorCorrection.realDivisorError
#print axioms BuildingBlocks.FloorCorrection.realDivisorError
#check BuildingBlocks.FloorCorrection.factorialIntegralRemainder
#print axioms BuildingBlocks.FloorCorrection.factorialIntegralRemainder
#check BuildingBlocks.FloorCorrection.log_stirlingSeq_upper
#print axioms BuildingBlocks.FloorCorrection.log_stirlingSeq_upper
#check BuildingBlocks.FloorCorrection.factorialIntegralRemainder_stirling_bounds
#print axioms BuildingBlocks.FloorCorrection.factorialIntegralRemainder_stirling_bounds
#check BuildingBlocks.FloorCorrection.realFloorCorrection
#print axioms BuildingBlocks.FloorCorrection.realFloorCorrection
#check BuildingBlocks.FloorCorrection.floorCorrectionMean
#print axioms BuildingBlocks.FloorCorrection.floorCorrectionMean
#check BuildingBlocks.FloorCorrection.floorCorrection_centered_remainder
#print axioms BuildingBlocks.FloorCorrection.floorCorrection_centered_remainder

#check BuildingBlocks.HyperbolaProduct.sum_divisors_eq_sum_factor_pairs
#print axioms BuildingBlocks.HyperbolaProduct.sum_divisors_eq_sum_factor_pairs
#check BuildingBlocks.HyperbolaProduct.moebius_divisor_sum
#print axioms BuildingBlocks.HyperbolaProduct.moebius_divisor_sum
#check BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient
#print axioms BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient
#check BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient_small
#print axioms BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient_small
#check BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient_complement
#print axioms BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient_complement
#check BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient_weighted_sum
#print axioms BuildingBlocks.HyperbolaProduct.hyperbolaProductCoefficient_weighted_sum

#check BuildingBlocks.RegularSource.reciprocal_square_sum_Icc_bound
#print axioms BuildingBlocks.RegularSource.reciprocal_square_sum_Icc_bound
#check BuildingBlocks.RegularSource.multiples_Ioc_card
#print axioms BuildingBlocks.RegularSource.multiples_Ioc_card
#check BuildingBlocks.RegularSource.natCast_div_lower
#print axioms BuildingBlocks.RegularSource.natCast_div_lower
#check BuildingBlocks.RegularSource.multiples_Ioc_card_bound
#print axioms BuildingBlocks.RegularSource.multiples_Ioc_card_bound
#check BuildingBlocks.RegularSource.squarefreeWindow
#print axioms BuildingBlocks.RegularSource.squarefreeWindow
#check BuildingBlocks.RegularSource.squarefulWindow
#print axioms BuildingBlocks.RegularSource.squarefulWindow
#check BuildingBlocks.RegularSource.squarefulWindow_subset_square_multiples
#print axioms BuildingBlocks.RegularSource.squarefulWindow_subset_square_multiples
#check BuildingBlocks.RegularSource.squarefulWindow_card_bound
#print axioms BuildingBlocks.RegularSource.squarefulWindow_card_bound
#check BuildingBlocks.RegularSource.squarefreeWindow_card_lower
#print axioms BuildingBlocks.RegularSource.squarefreeWindow_card_lower
#check BuildingBlocks.RegularSource.squarefree_terminal_half_lower
#print axioms BuildingBlocks.RegularSource.squarefree_terminal_half_lower
#check BuildingBlocks.RegularSource.signedMobiusInverse
#print axioms BuildingBlocks.RegularSource.signedMobiusInverse
#check BuildingBlocks.RegularSource.moebius_square_sum_ge_squarefree_half
#print axioms BuildingBlocks.RegularSource.moebius_square_sum_ge_squarefree_half
#check BuildingBlocks.RegularSource.larger_power_not_eventually_bounded
#print axioms BuildingBlocks.RegularSource.larger_power_not_eventually_bounded
#check BuildingBlocks.RegularSource.normalizedMobiusFunctional
#print axioms BuildingBlocks.RegularSource.normalizedMobiusFunctional
#check BuildingBlocks.RegularSource.normalizedMobiusFunctional_apply
#print axioms BuildingBlocks.RegularSource.normalizedMobiusFunctional_apply
#check BuildingBlocks.RegularSource.sqrt_normalized_source_bound
#print axioms BuildingBlocks.RegularSource.sqrt_normalized_source_bound
#check BuildingBlocks.RegularSource.sqrtNormalizedSource
#print axioms BuildingBlocks.RegularSource.sqrtNormalizedSource
#check BuildingBlocks.RegularSource.sqrtNormalizedSource_norm_le
#print axioms BuildingBlocks.RegularSource.sqrtNormalizedSource_norm_le
#check BuildingBlocks.RegularSource.sqrtNormalizedSource_recovery
#print axioms BuildingBlocks.RegularSource.sqrtNormalizedSource_recovery
#check BuildingBlocks.RegularSource.sourceTent
#print axioms BuildingBlocks.RegularSource.sourceTent
#check BuildingBlocks.RegularSource.sourceTent_nonneg
#print axioms BuildingBlocks.RegularSource.sourceTent_nonneg
#check BuildingBlocks.RegularSource.sourceTent_le
#print axioms BuildingBlocks.RegularSource.sourceTent_le
#check BuildingBlocks.RegularSource.sourceTent_zero
#print axioms BuildingBlocks.RegularSource.sourceTent_zero
#check BuildingBlocks.RegularSource.sourceTent_center
#print axioms BuildingBlocks.RegularSource.sourceTent_center
#check BuildingBlocks.RegularSource.sourceTent_abs_sub_le
#print axioms BuildingBlocks.RegularSource.sourceTent_abs_sub_le
#check BuildingBlocks.RegularSource.finite_sup_abs_sub_le
#print axioms BuildingBlocks.RegularSource.finite_sup_abs_sub_le
#check BuildingBlocks.RegularSource.signedTentEnvelope
#print axioms BuildingBlocks.RegularSource.signedTentEnvelope
#check BuildingBlocks.RegularSource.signedTentEnvelope_nonneg
#print axioms BuildingBlocks.RegularSource.signedTentEnvelope_nonneg
#check BuildingBlocks.RegularSource.signedTentEnvelope_le
#print axioms BuildingBlocks.RegularSource.signedTentEnvelope_le
#check BuildingBlocks.RegularSource.signedTentEnvelope_abs_sub_le
#print axioms BuildingBlocks.RegularSource.signedTentEnvelope_abs_sub_le
#check BuildingBlocks.RegularSource.smoothTestSource
#print axioms BuildingBlocks.RegularSource.smoothTestSource
#check BuildingBlocks.RegularSource.smoothTestSource_abs_le
#print axioms BuildingBlocks.RegularSource.smoothTestSource_abs_le
#check BuildingBlocks.RegularSource.smoothTestSource_abs_sub_le
#print axioms BuildingBlocks.RegularSource.smoothTestSource_abs_sub_le
#check BuildingBlocks.RegularSource.smoothTestSource_increment_le
#print axioms BuildingBlocks.RegularSource.smoothTestSource_increment_le
#check BuildingBlocks.RegularSource.cubic_quotient_lower
#print axioms BuildingBlocks.RegularSource.cubic_quotient_lower
#check BuildingBlocks.RegularSource.cubic_quotient_gap
#print axioms BuildingBlocks.RegularSource.cubic_quotient_gap
#check BuildingBlocks.RegularSource.cubic_quotient_abs_gap
#print axioms BuildingBlocks.RegularSource.cubic_quotient_abs_gap
#check BuildingBlocks.RegularSource.cubic_quotient_tail_gap
#print axioms BuildingBlocks.RegularSource.cubic_quotient_tail_gap
#check BuildingBlocks.RegularSource.signedTentEnvelope_at_quotient
#print axioms BuildingBlocks.RegularSource.signedTentEnvelope_at_quotient
#check BuildingBlocks.RegularSource.smoothTestSource_at_small_divisor
#print axioms BuildingBlocks.RegularSource.smoothTestSource_at_small_divisor
#check BuildingBlocks.RegularSource.signedTentEnvelope_zero_below
#print axioms BuildingBlocks.RegularSource.signedTentEnvelope_zero_below
#check BuildingBlocks.RegularSource.smoothTestSource_at_large_divisor
#print axioms BuildingBlocks.RegularSource.smoothTestSource_at_large_divisor
#check BuildingBlocks.RegularSource.smoothTestSource_sq_le
#print axioms BuildingBlocks.RegularSource.smoothTestSource_sq_le
#check BuildingBlocks.RegularSource.smoothTestSource_abs_le_sqrt
#print axioms BuildingBlocks.RegularSource.smoothTestSource_abs_le_sqrt
#check BuildingBlocks.RegularSource.signedMobiusInverse_smoothTestSource
#print axioms BuildingBlocks.RegularSource.signedMobiusInverse_smoothTestSource
#check BuildingBlocks.RegularSource.signedMobiusInverse_smoothTestSource_lower
#print axioms BuildingBlocks.RegularSource.signedMobiusInverse_smoothTestSource_lower
#check BuildingBlocks.RegularSource.signedMobiusInverse_no_uniform_regular_bound
#print axioms BuildingBlocks.RegularSource.signedMobiusInverse_no_uniform_regular_bound
#check BuildingBlocks.RegularSource.sourceDifferenceConstraint
#print axioms BuildingBlocks.RegularSource.sourceDifferenceConstraint
#check BuildingBlocks.RegularSource.sourceDifferenceConstraint_apply
#print axioms BuildingBlocks.RegularSource.sourceDifferenceConstraint_apply
#check BuildingBlocks.RegularSource.regularSourceSpace
#print axioms BuildingBlocks.RegularSource.regularSourceSpace
#check BuildingBlocks.RegularSource.regularSourceNormedSpace
#print axioms BuildingBlocks.RegularSource.regularSourceNormedSpace
#check BuildingBlocks.RegularSource.mem_regularSourceSpace
#print axioms BuildingBlocks.RegularSource.mem_regularSourceSpace
#check BuildingBlocks.RegularSource.regularSourceSpace_isClosed
#print axioms BuildingBlocks.RegularSource.regularSourceSpace_isClosed
#check BuildingBlocks.RegularSource.sourceDifferenceSequence
#print axioms BuildingBlocks.RegularSource.sourceDifferenceSequence
#check BuildingBlocks.RegularSource.liftRegularSource
#print axioms BuildingBlocks.RegularSource.liftRegularSource
#check BuildingBlocks.RegularSource.liftRegularSource_norm_le
#print axioms BuildingBlocks.RegularSource.liftRegularSource_norm_le
#check BuildingBlocks.RegularSource.regularMobiusFunctional
#print axioms BuildingBlocks.RegularSource.regularMobiusFunctional
#check BuildingBlocks.RegularSource.regularMobiusFunctional_apply
#print axioms BuildingBlocks.RegularSource.regularMobiusFunctional_apply
#check BuildingBlocks.RegularSource.regularMobiusFunctional_lift
#print axioms BuildingBlocks.RegularSource.regularMobiusFunctional_lift
#check BuildingBlocks.RegularSource.regularMobiusFunctional_not_uniformly_bounded
#print axioms BuildingBlocks.RegularSource.regularMobiusFunctional_not_uniformly_bounded
#check BuildingBlocks.RegularSource.regularSpaceSource
#print axioms BuildingBlocks.RegularSource.regularSpaceSource
#check BuildingBlocks.RegularSource.regularSpaceSource_bounds
#print axioms BuildingBlocks.RegularSource.regularSpaceSource_bounds
#check BuildingBlocks.RegularSource.regularMobiusFunctional_scaled_source
#print axioms BuildingBlocks.RegularSource.regularMobiusFunctional_scaled_source
#check BuildingBlocks.RegularSource.exists_fixed_regular_source_with_unbounded_inverse
#print axioms BuildingBlocks.RegularSource.exists_fixed_regular_source_with_unbounded_inverse
